### ISSUE TITLE
Reducing friction between region and active object

### ISSUE THREAD

**Issue by Wetlize** [clemera/objed#66]
I feel like all top-level commands that able to work on the (transient) region should just-work™ without having the user to perform manual bookkeeping. As an example, activating objed and doing `M-u` (`upcase-dwim`/`upcase-region`) should automatically apply the command on the current object without additionally activating region.

The same thing should apply to non-linearly marked objects. Additionally, the user shouldn't add such commands to `objed-keeper-commands`.

The current solution is to explicitly map each such command as objed's operation using `objed-define-op` and then bind each operation in an objed "friendly" keymap. As example:
```emacs-lisp
(define-key objed-map "M-u" (objed-define-op nil upcase-region)
```
I feel like it's fine to have `objed-define-op`, but it should only be reserved for more specialized/specific cases.

I do understand that this might be difficult to do so, at least with 100% accuracy, as this most likely will require some kind heuristic-based lookup, since not all top-level commands are reserved for the region based commands. But I might be wrong and there's a potentially unknown solution for this?

**Comment by clemera** [comment]
Thanks, that are good points. I want to redesign the activate/deactivate logic at some point. I'm curious do you use `objed-mode` or use `objed-activate` to activate objed manually? 

The current deactivate behavior is similar to isearchs behavior. Any command not bound in the transient map defaults to exit and execute the regular Emacs command. An easy way that would probably work for allowing any region command to apply on the last object would be that objed pushes the mark on the other object side on exit. But this would still exit objed by default unless you add those commands to `objed-keeper-commands`.

There are indeed ways you can use to detect most region commands, those could be used to keep objed active after region commands (configurable via an user option).

Are you aware of `objed-op-x` which you can invoke with `x TAB` by default?

**Comment by Wetlize** [comment]
> I'm curious do you use objed-mode or use objed-activate to activate objed manually?

I do use `objed-mode`, but I set `objed-auto-init` to nil, though this might be temporary and I might change this in future to auto-init if any command from `objed-cmd-alist` executes 2 consecutive times in a row.

Right now though, when `objed-mode` is active I use either, `objed-activate-object` (bound to `M-o`) or `objed-activate` (bound to `C-,`) with `objed-initial-object` set to `'region`, so it behaves akin to `exchange-point-and-mark`.

> An easy way that would probably work for allowing any region command to apply on the last object would be that objed pushes the mark on the other object side on exit. But this would still exit objed by default unless you add those commands to objed-keeper-commands.

I don't mind this as a temporary workaround, but this is still less than optimal, because `-dwim` based commands will still require an explicitly active region (instead of just coordinates of point and mark). Besides, how would this work with marked objects?

> There are indeed ways you can use to detect most region commands, those could be used to keep objed active after region commands (configurable via an user option).

I feel like both your solutions can be used together, since they don't conflict with each other. Just like you mentioned, the user could disable/enable them with provided user options.

I wonder if there's way to somehow fake `region-active-p` to return t when objed is active (without any active region) and make `region-beginning`/`region-end` return bounds of the current object.

> Are you aware of objed-op-x which you can invoke with x TAB by default?

I am, but this is now another kind of friction. This is because when editing I want to operate quickly (at a subconscious level), without having to refocus my attention on the selection of the editing operation from a popup list.

The command is fine though, but not for casual usage (at least for me most of the time). Doing something like `M-o l M-u` is quicker than `M-o l C-SPC M-u` and even more quicker than `M-o l x TAB upcase- RET` Additionally, the command is heuristic-based, so if it fails to find a needed command (e.g. it can't find line sorting commands), you have to resort to a different solution, refocusing your attention further.

**Comment by clemera** [comment]
> I don't mind this as a temporary workaround, but this is still less than optimal, because -dwim based commands will still require an explicitly active region (instead of just coordinates of point and mark). Besides, how would this work with marked objects?

It wouldn't ;) 

> I wonder if there's way to somehow fake region-active-p to return t when objed is active (without any active region) and make region-beginning/region-end return bounds of the current object.

Actually that might be possible, looking at the implementation of `region-active-p` and region-beginning/end just return point/mark position which could be set each time an object is chosen. I have experiment with that.

> The command is fine though, but not for casual usage (at least for me most of the time). Doing something like M-o l M-u is quicker than M-o l C-SPC M-u and even more quicker than M-o l x TAB upcase- RET Additionally, the command is heuristic-based, so if it fails to find a needed command (e.g. it can't find line sorting commands) you have to resort to a different solution, refocusing your attention further.

I'm certainly interested making the quickest and natural way possible. I will see what I can come up with, patches welcome of course ;)

**Comment by clemera** [comment]
Could you try branch `#66 ` and give it some testing?

**Comment by Wetlize** [comment]
So far I didn't found any problems with commands that supposed to manipulate exclusively on regions (like `upcase-region` or `align`). Was pleasantly surprised that you improved the heuristic, so sorting commands now detected too.

The region commands that involve minibuffer prompts working too (e.g. aligning), but right now they will exit objed after applying the command.

Commands that use `region-active-p`/`use-region-p`/`region-beginning`/`region-end`, such as `[name]-dwim` based commands (e.g. `upcase-dwim` or `comment-dwim`) do not work. I guess this is expected right now (by looking up on the commit's code).

If you mark multiple objects and execute a top-level region based command it will only apply command on the currently active object. It would be amazing if you would be able to somehow apply such combos on marked objects too.

**Comment by clemera** [comment]
Thanks, 

> The region based commands that involve minibuffer prompts (like aligning) do work

Which one worked for you? This seem to be broken for me.

> Commands that use internally region-active-p/use-region-p/region-beginning/region-end, such as [name]-dwim based commands (e.g. upcase-dwim or comment-dwim) do not work on objed's bounds, because they don't recognize an active region.

The were not detected as region commands I improved it but there might be problems this is all experimental ;)

>  It would be amazing if you would be able to somehow apply such combos on marked objects too.

I will look into that once everything works for on object.

**Comment by clemera** [comment]
First version to work with multiple objects is implemented. Furthermore other region commands which don't have a region command signature are now recognized but I'm not very happy with this approach because there could be some commands which break things. 

Using region commands which need the minibuffer does still not work for me. But I think this can be fixed.

**Comment by Wetlize** [comment]
I did more tested with the new updates and here what I've found so far:
- Some dwim based commands (like `upcase-region`/`comment-dwim`) that use `region-active-p`/`use-region-p` working as extended, but other commands (like `fill-paragraph`) do not work with objed's selection. I suspect this is because such commands use a different method for detection of an active region, such as checking for `transient-mark-mode` and `mark-active` variables.
- `M-x` doesn't work anymore with active objed. Not a biggie for me, but something that should probably be reported.
- I tested region commands that require prompts, such as `query-replace`, `align`, `sort-regexp-fields`. All these worked for me. What commands didn't work for you?

**Comment by Wetlize** [comment]
I also tried the all mentioned commands by marking multiple objects and they work as you would expect (repeating the previously mentioned behaviors). I was able to catch weird bug though, but only with `comment-dwim` so far:

1. Mark multiple objects.
2. Run `comment-dwim` (`C-;`).
3. Do `objed-last` to reactivate marks; observe that marks do not have the same bounds as previously, but they're pretty close to initial one.
4. Repeat step 2.
5. Observe that the commands didn't apply on marked.

I suspect that this is not a regression since the same happens if you use `objed-objed-comment-or-uncomment-region`, so this might need a separate issue.

**Comment by clemera** [comment]
Thank you for the tests! With latest commits I was able to fix some of the bugs you discovered:

> However, other commands (like fill-paragraph) do not work with objed's selection. I suspect this is because such commands use a different method for detection of an active region, such as checking for transient-mark-mode and mark-active variables

Those should work now, there might still be commands which will not work but I had to decide to include those or to run commands which potentially break things and decided for the safer variant. Most commands should be catched, though.

> M-x doesn't work anymore while objed is active. Not a biggie for me, but something that should probably be reported.

Should work again?

> I tested region commands that require prompts, such as query-replace, align, sort-regexp-fields. All these worked for me, but they will deactivate objed after the execution. What commands didn't work for you?

Strange those don't work for me, maybe something config related. When I get the prompt objed stays active and I can not type things because objed is stil catching keys, I have to investigate. I will continue to work on the multiple commands problems later.

**Comment by clemera** [comment]
> Strange those don't work for me, maybe something config related.

Indeed it was config related. Those commands can not be reliable detected, and should be added to keeper commands. I have to implement to make region commands work with the keeper command list first, though.

**Comment by clemera** [comment]
> Strange those don't work for me, maybe something config related.

This was my current config together with a bug that I fixed on master.

**Comment by Wetlize** [comment]
> Those should work now

They still don't work. I tested it with some commands from external packages, but they use the same strategy for sniffing the active region as `fill-paragraph`, which doesn't work either.

> Should work again?

It does, but it regressed `query-replace`. Don't get me wrong, the command is still functional, but it doesn't catch objed's selection now. The `align` command is still working though.

I feel like the behavior was better with the previous version, the only thing which was broken back then is `M-x`.

> I had to decide to include those or to run commands which potentially break things and decided for the safer variant. Most commands should be catched, though.

If there will be no better way to solve this, then is it possible to expose this as a user option, so he would enable this on his own risk? Because I haven't seen anything seriously broken so far, which makes such option more worthwhile for me. It could be exposed as a special value in `objed-integrate-region-commands`.

**Comment by clemera** [comment]
> They still don't work. I tested it with some commands from external packages, but they use the same strategy for sniffing the active region as fill-paragraph, which doesn't work either.

Could you describe your test case because it works for me. For example given:

    ;; alkaj ldjf lkas jdflkjaslfd jlksa jfdlk jdsalfj alskdf jlkaj flkjsl jdflk jasfdlk jasld jflasjd f
    ;;
    ;; akdsfkja hsdkf hakjs fkja hdsfkjha kjfds hkja hfdskj hakjf hkjasd hfkja hfdkj hakjfd hakjshd fkjhaf


I can select the paragraph and use fill-paragraph to fill region as pragraph.

**Comment by Wetlize** [comment]
```
;; alkaj ldjf lkas jdflkjaslfd jlksa jfdlk jdsalfj alskdf jlkaj flkjsl jdflk jasfdlk jasld jflasjd f
;; akdsfkja hsdkf hakjs fkja hdsfkjha kjfds hkja hfdskj hakjf hkjasd hfkja hfdkj hakjfd hakjshd fkjhaf
```
Select line object, do `fill-paragraph`, expected: 
```
;; alkaj ldjf lkas jdflkjaslfd jlksa jfdlk jdsalfj alskdf jlkaj flkjsl jdflk
;; jasfdlk jasld jflasjd f
;; akdsfkja hsdkf hakjs fkja hdsfkjha kjfds hkja hfdskj hakjf hkjasd hfkja hfdkj hakjfd hakjshd fkjhaf
```
The actual output:
```
;; alkaj ldjf lkas jdflkjaslfd jlksa jfdlk jdsalfj alskdf jlkaj flkjsl jdflk
;; jasfdlk jasld jflasjd f akdsfkja hsdkf hakjs fkja hdsfkjha kjfds hkja hfdskj
;; hakjf hkjasd hfkja hfdkj hakjfd hakjshd fkjhaf
```

**Comment by clemera** [comment]
I get the expected one not sure what is going on, are you using a1f448009?

**Comment by Wetlize** [comment]
> I get the expected one not sure what is going on, are you using a1f4480?
Yep, just verified again more rigorously.

**Comment by clemera** [comment]
Okay, I get the same behavior as you with `emacs -Q` I have to check.

**Comment by Wetlize** [comment]
> I guess you haven't tried with most recent changes, because this works for me, too.

Well, it only works with some commands now. I had previously remapped `query-replace` commands to [anzu ones](https://github.com/syohex/emacs-anzu), so I removed the remap and the default `query-replace` work as expected, but anzu's one don't (they worked previously though).

**Comment by clemera** [comment]
Problem was by default fill-paragraph was in objed-keeper-commands and that was tested before region integration commands, this is fixed now. Anzu does not work because it fails the safety check which boils down to simply checking if the docstring contains "region" or the symbol name dontains "dwim" which anzu doesn't.

**Comment by clemera** [comment]
I will maintain a list of popular commands which are not auto detected, I feel that is still better than using an unsafe approach. With latest commit anzu should work again.

**Comment by Wetlize** [comment]
Okay. I'm still stress testing this branch and should probably report what I found so far. 

There's package called [drag-stuff](https://github.com/rejeep/drag-stuff.el) that work similarly to `objed-move-[direction]` commands. The main commands from this list are not recognized by the heuristic, so I've added them myself out of interest:
```emacs-lisp
(dolist (cmd '(drag-stuff-down drag-stuff-up drag-stuff-left drag-stuff-right)
  (push cmd objed--known-region-commands))
```
Now, they being of recognized, but work pretty badly. When you move stuff with objed's selection using these commands it will move things, but not how you would expect. It will either, move thing as you would expect, move more things than selected or will start randomly shuffle/rotate text.

Is this overall limitation? Commands that will move selected things are not gonna be able to work robustly?

**Comment by clemera** [comment]
I think more generally it would be better to exit objed after executing a region command. This avoids lots of problems... Objed can't integrate with arbitrary region commands it does not know anything about, but exit with them and then continue to work with the region is possible.

**Comment by clemera** [comment]
And for commands which you would like to keep objed active you can add the commands to keeper commands like with other commands, too. I will go implement that.

**Comment by clemera** [comment]
I have improved working with marked objects, too. Things should mostly work now. By default objed will exit after a region command, now. You can add commands which are able to keep object active to `objed-keeper-commands`.

**Comment by Wetlize** [comment]
I'll test this out. I still have some niche case where I would like to get your input. In my config I have a bunch of menu-items bindings that change active commands base on `(region-active-p)` checks, e.g.:

```emacs-lisp
(global-set-key [backtab] '(menu-item "" nil :filter
                            (lambda
                              (&optional _)
                              (cond
                               ((region-active-p)
                                (function indent-rigidly))
                               (t
                                (function indent-relative)))))
```

Right now such bindings don't pass the conditional check, e.g. if I active object and hit `[backtab]` it will always dispatch to `indent-relative`, unless I manually activate region. I guess in private configs this can be solved by making objed expose a global variable/function that will yield its current state, e.g. `objed-active-p`?

So later I would write:
```emacs-lisp
(defun my-region-active-p ()
  (or object-active-p (region-active-p)))
```

I can implement it myself with objed's init/exit hooks, but it's probably make sense for objed provide such thing itself?

**Comment by clemera** [comment]
I think you could advice `region-active-p` for that. While dispatching via the menu item `this-command` is not bound so you can avoid affecting commands by checking for that, maybe something like:

    (define-advice region-active-p (:before-until () detect-objed)
      (and (not this-command)
           objed--buffer))

**Comment by clemera** [comment]
You should be able to use `objed--buffer` variable to detect if objed is active.

**Comment by Wetlize** [comment]
I did more testing and overall satisfied with how region based commands are working right now. Especially since how easy I can reactive last objed selection back with `objed-activate`. There's still some bugs though. 

- Prompt based commands still don't completely apply on marked objects. They only apply on the first marked object and after that they exit with `exit-minibuffer: No catch for tag: exit, nil` error.
- If you execute a prompt based command on objed's selection and then quit the prompt without completing the command (e.g. using `keyboard-quit`) the region will still remain active. I don't think it's a big deal or even bug, except sometimes it places mark where the point is, making it not obvious that the region is still active after abortion of the prompt.

These are low priority and might be needed a separated issue:
- [This bug](https://github.com/clemera/objed/issues/66#issuecomment-569495271) is still here.
- Some commands don't apply from `objed-op-x`. I was only able to catch this with sorting commands so far.

There's probably more, so I think it's better to not merge this for some time (a week or two).

**Comment by clemera** [comment]
> Prompt based commands still don't completely apply on marked objects. They only apply on the first marked object and after that they exit with exit-minibuffer: No catch for tag: exit, nil error.

Could you give a more detailed example? I tried with align, and query-replace but those seem to work correctly for me.

**Comment by clemera** [comment]
BTW, I added M-x commands to region commands, this makes it very natural to invoke a region command via M-x on the current object(s).

**Comment by Wetlize** [comment]
> If you execute a prompt based command on objed's selection and then quit the prompt without completing the command (e.g. using keyboard-quit) the region will still remain active. I don't think it's a big deal or even bug, except sometimes it places mark (after prompt abortion) where the point is, making it not obvious to know that the region is still active.

I find out this is not objed's fault. Some commands just alter position of mark after abnormal exit from the prompt, so this probably can be completely ignored or marked as low priority for a while.

**Comment by Wetlize** [comment]
> Could you give a more detailed example? I tried with align-regexp, and query-replace but those seem to work correctly for me.

These work for me too. I'm able to reproduce this with third party packages, like [anzu](https://github.com/syohex/emacs-anzu)'s versions of `query-replace` and [ialign](https://github.com/mkcms/interactive-align).

They both produce the same `exit-minibuffer: No catch for tag: exit, nil` error. They backtrace is the same too:
``` emacs-lisp
Debugger entered--Lisp error: (no-catch exit nil)
  throw(exit nil)
  exit-minibuffer()
  funcall-interactively(exit-minibuffer)
  call-interactively(exit-minibuffer nil nil)
  command-execute(exit-minibuffer)
```

> I also tired with objed-case-op which you mentioned earlier but it works on all marked objects (it queries for each one).

`objed-objed-case-op` somehow doesn't always work for me correctly, sometimes it applies on all marked objects, sometimes only on some of them and sometimes, either, on an object at point (even though there's marked one) or random line/s.

Sometimes it can even error with `The mark is not set now, so there is no region`, I assume this happens when you open a new buffer without any marks in it.

All this can also happen without marked objects. The command was somehow bogus (albeit, not this much) even before the branch for this issue was created; I just never reported it back.

**Comment by Wetlize** [comment]
> BTW, I added M-x commands to region commands, this makes it very natural to invoke a region command via M-x on current object(s).

Yeah, I agree. It also helped me to catch a bug that I was not able to previously reproduce successfully, so I didn't report it back. Sometimes objed doesn't cleanup marking overlays after exiting it. Steps to reproduce:
1. Mark multiple objects
2. Do `M-x` or a prompt based command that was not defined with `objed-define-op`.
3. Quit minibuffer (and objed if didn't already).
4. Observe that marks are still visible in the buffer.

If you activate objed back, the marks will not be recognized as real, but you can cleanup them by manually hitting `m`/`M` on each of them.

**Comment by clemera** [comment]
I have removed the M-x functionality for now, because I had some issues when there is only one marked object. I want first fix all the problems that still exists with the region commands. First I will tackle the anzu error you describe.

> Wouldn't it also better to execute the same command for each marked object, instead of prompting each time for a new one, like objed-op-x does?

Yes, I also think that commands like `query-replace` should only prompt once with marked objects. But we are getting to much in this issue already. I will see what feature improvements are left and create new issues for them once this issue can be closed.

**Comment by clemera** [comment]
I have disabled prompting commands completely. I think it's better to have an separate issue for those. Please report any further issues with commands you try in this issue the next few weeks. [This](https://github.com/clemera/objed/issues/66#issuecomment-569495271) is expected (see docstring of `objed-last`) but it would be great to open an issue for making `objed-last` work with buffer changes.

**Comment by clemera** [comment]
Sorry this is still buggy, I have to think a bit and try a few other things. I will let you know when this is in a testable state again.

**Comment by clemera** [comment]
Okay, I think things are working correctly again. Prompting commands just don't work with multiple marked objects for now, I will open a separate issue once this is closed.

**Comment by Wetlize** [comment]
Hi, I've catched a new bug. Here's recipe to reproduce it:

1. Activate objed.
2. Activate region.
3. Extend objed however you'd like to (I only tested with line based extension).
4. Activate a top level region-based command.
5. Observe that the command didn't apply on the whole selection.

**Comment by clemera** [comment]
Thanks! Should be fixed by b495848f21d6d2702d7ba99951375920cd9b5b92

**Comment by Wetlize** [comment]
Not a bug, but I've found a new unhandled case. So I've tried to [swap regions](https://github.com/xuchunyang/swap-regions.el) using objed's selection and it kind of working, but not completely.

Right now it only able to recognize the first selection successfully ([this part of the function](https://github.com/xuchunyang/swap-regions.el/blob/master/swap-regions.el#L61-L74)), but after selecting the second object and exiting the recursive editing it's not able to recognize the second region. As a result, it exiting the `swap-region` function and does nothing after (excepting clearing the overlay).

Is there anything at your side that needs to be handled in objed for this case? Or I need to hack this function myself (or write my own implementation)? It's not a biggie for me, but probably worth informing.

**Comment by clemera** [comment]
Thanks, I fixed it by just always setting the region positions on exit. Hopefully this will not introduce other problems but I can't think of any right now.

**Comment by Wetlize** [comment]
Unfortunately this is a bit aggressive since it takes control over the position of point. I often use objed just to select a text object, toggle it side and do something else on the other side. Right now (each time on exit) it will move point to the left side of the selected object.

**Comment by clemera** [comment]
Oh, sorry, will fix that tomorrow

**Comment by clemera** [comment]
Works again!
